### ISSUE TITLE
Inconsistant copyright year and author information

### ISSUE THREAD

**Issue by jame** [Template-Toolkit-Latex/Template-Latex#10]
The copyright years and author information in the comment headers and in the module POD are inconsistent and not up-to-date. which also means that man and doc files that are created while building a Debian package (which was being worked on when I found the issues) for the module do not have the correct information. Also; the lib/Template/Plugin/Latex.pm file as well as the README file do not have the updated information. Reference also the ticket opened for the same issue when v3.06 was released:
https://rt.cpan.org/Ticket/Display.html?id=96957

**Comment by jame** [comment]
My attempt at a patch for this issue, created for the Debian package, can be seen at:
https://anonscm.debian.org/git/pkg-perl/packages/libtemplate-plugin-latex-perl.git/tree/debian/patches/Documentation.patch

Note that it may be incomplete.

**Comment by einhverfr** [comment]
fixed
